var xhrDA=new function(){function f(){var a=$("#xhr-error");a.length&&(a=a.attr("type"),undebug("1 error: "+a),j(a))}function j(a){var b="",e="";a=="session_expired"?(b="Session Expired",e=k+" is unable to process this request because the session has expired. <br/>"):a.substring(0,1)=="4"?(b="File not Found",e=k+" was unable to complete your request. <br/>The file you are looking for might have been removed, had its name changed, or is temporarily unavailable. <br/>"):a.substring(0,1)=="5"?(b="Internal Server Error",
e=k+" was unable to complete your request. <br/>"):b="Error: "+a;$("#xhr_ie").length||g.html('<link type="text/css" rel="stylesheet" href="https://'+window.location.host+'/ma/common/css/errors.css"/><div id="xhr_ie"><div id="xhr_ie_dialog"></div></div>');$("#xhr_ie_dialog").html('<h1 id="xhr_ie_title">'+b+'</h1><div id="xhr_ie_msg">'+e+'</div><button id="xhr_ie_action" onclick="javascript:xhrDA.clearErrorDialog();">Go back to the previous page</button>')}function l(a){a&&a.indexOf("xhr-error")>=0&&
(a=a.replace("<xhr-error",'<div id="xhr-error" '),a=a.replace("</xhr-error","</div"),g.html(a))}function r(a,b,e,d){var c="",q={};this.addParam=function(a,b){c&&(c+="&");c+=encodeURIComponent(a)+"="+encodeURIComponent(b)};this.addParams=function(a){for(p in a)this.addParam(p,a[p])};this.setRequestEntity=function(a){c=a};this.setRequestHeader=function(a,c){q[a]=c};this.execute=function(n,f){$.ajax({type:"POST",url:"/mt/ws/"+a+"/"+b+"/"+e,headers:q,data:c,dataType:d,success:function(a,c,b){n(a,b)},
error:function(a){f(a.responseText)}})};this.getParams=function(){return c}}var g,h,m=!1,o=!1,k="Usablenet";this.init=function(a){g=$("#xhr-content");jQuery.ajaxSetup({beforeSend:function(b){b.setRequestHeader("x-jtt-platform",a.platform);h==""&&(h=" ");b.setRequestHeader("xhr-referer",h)}});if(a.company)k=a.company;$(document).bind("xhrloaded",f)};this.clearErrorDialog=function(){undebug("clear dialog");xhrDA.back()||window.location.reload()};this.setReferrer=function(a){h=a};this.getReferrer=function(){return h};
this.loadPage=function(a,b){var e=$.extend({},{target:"#xhr-content",cacheData:!0,callback:function(){}},b),d=this;(o=m&&e.target=="#xhr-content")&&xhrDA.loadPageAnimation.fadein();$.ajax({url:a,type:"GET",success:function(c,b,n){(b=n.getResponseHeader("xhr-location"))?(d.loadPage(b,e),h=b):($(e.target).html(c),l(c),h=a,xhrDA.bindContent({target:e.target,data:c,url:a,cacheData:e.cacheData}),e.callback(),o&&xhrDA.loadPageAnimation.fadeout(),$(document).trigger("xhrloaded"))},error:function(a){undebug(a.responseText);
undebug(a.status);j(a.status.toString());o&&xhrDA.loadPageAnimation.fadeout()}});$(document).trigger("xhrloading")};this.sendForm=function(a){var b=this,e=a.form,d=$(e).serialize();a.name&&(a.type=="image"?(a.value&&(d=encParam(d,a.name,a.value)),d=encParam(d,a.name+".x","1"),d=encParam(d,a.name+".y","1")):d=a.value?encParam(d,a.name,a.value):encParam(d,a.name,"Submit"));var c=e.getAttribute("action");m&&xhrDA.loadPageAnimation.fadein();var f=function(a){l(a);$(document).trigger("xhrloaded");m&&xhrDA.loadPageAnimation.fadeout();
xhrDA.bindContent({data:a,cacheData:!0})};e.method.toUpperCase()=="GET"||e.method==""?(c.indexOf("?")!=-1&&(c=c.substring(0,c.indexOf("?"))),c+="?"+d,g.load(c,function(a,e,d){d.getResponseHeader("xhr-location")?(a=d.getResponseHeader("xhr-location"),b.loadPage(a),h=a):(h=c,f(a))})):$.post(c,d,function(a,e,d){d.getResponseHeader("xhr-location")?(a=d.getResponseHeader("xhr-location"),b.loadPage(a),h=a):(h=c,g.html(a),f(a))});$(document).trigger("xhrloading")};this.bindContent=function(a){var b=a.target?
$(a.target):g,e=a.target!="#xhr-content";if(e)a.data=g.html();if(a.cacheData)try{var d=$(b[0].getElementsByTagName("xhr-page"));i.current=d.attr("xhr-id")&&a.data;if(i.current){if(e)a.url=!1;i.add(d.attr("xhr-id"),d.attr("xhr-title"),a.data,a.url)}}catch(c){undebug("xhrDA Error. Wrong xhr format. "+c)}b.find("a").click(function(a){var b=$(this),c=b.attr("href");if(!b.attr("onclick")&&!(c.indexOf("#")==0||c.indexOf("/mt/")==-1))a.preventDefault(),xhrDA.loadPage(c)});b.find("form").find("input[type=submit], input[type=image]").click(function(a){var b=
$(this);b.attr("onclick")||(a.preventDefault(),xhrDA.sendForm(b[0]))})};this.loadPageAnimation=new function(){var a,b={},e,d=!0;this.init=function(c){m=!0;a=$(document.createElement("div")).attr("id","xhrLoadingOverlay").hide();a.css({height:"100%",width:"100%",top:"0",left:"0",background:'#FEFEFE url("/ma/common/images/loader1.gif") no-repeat 50% 50%'});g.parent().append(a);c&&jQuery.isPlainObject(c)&&(a.css(c),b=c);a.css({opacity:"0","z-index":"1001",position:"absolute"})};this.fadein=function(){b.height||
(d?(a.css("height","100%"),d=!1):(e<document.body.offsetHeight&&(e=document.body.offsetHeight+10),a.css("height",e)));a.show().animate({opacity:1},"500")};this.fadeout=function(){a.css("display","none");g.css({opacity:0}).animate({opacity:1},500,function(){b.height||(e=document.body.offsetHeight+10,a.css("height",e));g.css("opacity","")})}};var i=new function(){var a=[];this.current=!1;this.add=function(b,e,d,c){for(var f=0;f<a.length;f++)if(a[f][0]==b){c||(c=a[f][3]);a.splice(f,a.length-f);break}f=
d.indexOf("un_jtt_jse")&&d.indexOf("un_jtt_pid")?!0:!1;a.push([b,e,d,c,new Date,f])};this.peek=function(){return a.length>0?a[a.length-1]:null};this.pop=function(){this.current&&a.length>1&&a.splice(a.length-1,1);this.current=!0;return a.length>0?a[a.length-1]:null};this.home=function(){a.length?(a=[a[0]],xhrDA.back()):window.location.reload()};this.resetList=function(){a=[]}};this.resetHistory=function(){i.resetList();var a=$(g.get(0).getElementsByTagName("xhr-page"));a.attr("xhr-id")?i.add(a.attr("xhr-id"),
a.attr("xhr-title"),g.html(),""):i.current=!1};this.refresh=function(){var a=i.peek();a&&xhrDA.loadPage(a[3])};this.back=function(){var a=i.pop();return a?(a[5]||a[4]>new Date-42E4?(g.html(a[2]),xhrDA.bindContent({data:a[2]})):xhrDA.loadPage(a[3]),!0):!1};this.backHome=function(){i.home()};this.backToSafePage=function(){for(var a=i.pop();a;)if(a[3]){g.html(a[2]);xhrDA.bindContent({data:a[2]});break}};this.newWebService=function(a,b,e,d){return new r(a,b,e,d)};this.cookies={set:function(a,b,e,d){var c=
new Date;c.setTime(c.getTime()+d*1E3);a=a+"="+escape(b)+(d==null?"":";expires="+c.toUTCString());typeof e!="undefined"&&(a+=";path="+e);document.cookie=a},get:function(a){if(document.cookie.length>0&&(c_start=document.cookie.indexOf(a+"="),c_start!=-1)){c_start=c_start+a.length+1;c_end=document.cookie.indexOf(";",c_start);if(c_end==-1)c_end=document.cookie.length;return unescape(document.cookie.substring(c_start,c_end))}return""},remove:function(a){var b=new Date;b.setTime(b.getTime()-864E5);document.cookie=
a+("=; expires="+b.toString())}}};function encParam(f,j,l){f&&(f+="&");f+=encodeURIComponent(j)+"="+encodeURIComponent(l);return f}function escapeHTML(f){return f.split("&").join("&amp;").split("<").join("&lt;").split('"').join("&quot;")}function qualifyURL(f){var j=document.createElement("div");j.innerHTML='<a href="'+escapeHTML(f)+'">x</a>';return j.firstChild.href}function undebug(f){try{console.log(f)}catch(j){}}
function loadCSS(f){$.browser.msie?(document.createStyleSheet(f),undebug("IE loadCSS")):(f=$(document.createElement("link")).attr("rel","stylesheet").attr("href",f).attr("type","text/css"),$("head").append(f))}function loadJS(f){$.ajax({url:f,dataType:"script"})};
